services:
  - type: web
    name: codeswitch-benchmark
    runtime: python
    plan: free
    buildCommand: pip install -r requirements_web.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9

