services:
  - type: web
    name: codeswitch-benchmark
    env: python
    plan: free
    branch: main
    buildCommand: pip install --upgrade pip && pip install -r requirements_web.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 1 --timeout 120 app:app
    healthCheckPath: /
